### PR TITLE
Make temperature i32 instead of u32, because you know, it can get cold

### PR DESCRIPTION
**Pull request by twistedfall**
My mistake from the previous pull request, found out about it today when it got cold outside :)

### CODE REVIEW

**Comment by yuqio** [comment]
Thanks!
BTW The build errors are unrelated to your changes. I already submitted a [PR](https://github.com/Lymia/derive_setters/pull/3) upstream but I'll have to wait to merge this PR until a new version of `derive_setter` is released.

**Comment by yuqio** [comment]
Sorry for taking so long to merge this pull request. The upstream PR I opened has not been merged yet so I pinned the syn version to a specific version for now (d0dc3995db6dd9b274bd8fb93000d8c3b629a9fa). Let me know if you want me to release a new version.

**Comment by twistedfall** [comment]
No pressure :) I’m using the local fork with that fix applied atm

**Comment by yuqio** [comment]
Okay :) In that case I'll probably implement a different feature first, before I release a new version (but that shouldn't take too long, I will try to finish it tomorrow).

**Comment by yuqio** [comment]
It's now available in [version 0.12.0](https://github.com/yuqio/huelib-rs/releases/tag/v0.12.0) 🎉

**Pull request merged**
